sonar.organization=my-org
sonar.projectKey=perf-testing-app
sonar.projectName=perf-testing-app
sonar.sources=.
sonar.exclusions=node_modules/*, k6-v0.51.0-linux-amd64/*
sonar.javascript.node.jsEnv=true
