name: CI with Performance and Security Testing

on: [push, pull_request]

jobs:
  performance-and-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # ==========================================
    # TASK 6: SECURITY TESTING (SECURITY AUDIT)
    # ==========================================
    - name: Run Security Vulnerability Scan
      run: |
        echo "Starting Security Scan..."
        npm audit --json || true # || true lagaya hai taaki agar vulnerability mile toh pipeline fail na ho aur report dikhe

    # ==========================================
    # TASK 5: PERFORMANCE TESTING (K6)
    # ==========================================
    - name: Start App in Background
      run: |
        node index.js &
        sleep 5

    - name: Download and Run k6 Binary
      run: |
        wget https://github.com/grafana/k6/releases/download/v0.51.0/k6-v0.51.0-linux-amd64.tar.gz
        tar -xvzf k6-v0.51.0-linux-amd64.tar.gz
        sudo cp k6-v0.51.0-linux-amd64/k6 /usr/local/bin/
        k6 run script.js
