name: Performance Testing CI

on: [push, pull_request]

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and start app
      run: |
        npm install
        node index.js &
        sleep 5

    - name: Download and Run k6 Binary
      run: |
        wget https://github.com/grafana/k6/releases/download/v0.51.0/k6-v0.51.0-linux-amd64.tar.gz
        tar -xvzf k6-v0.51.0-linux-amd64.tar.gz
        sudo cp k6-v0.51.0-linux-amd64/k6 /usr/local/bin/
        k6 run script.js
